### ISSUE TITLE
Consider using Immutables.org instead of lombok

### ISSUE THREAD

**Issue by queer** [mewna/catnip#163]
https://immutables.github.io/

**Comment by napstr** [comment]
### Background:
Lombok while being on the frontier of creating convenience annotations for Java since forever frequently has trouble working together with other annotation processors, as well as Java version upgrades. I think most of the issues are due to its core principle of modifying existing source files instead of fully generating them, but the reason is probably irrelevant in the face of the fact that it is con.

There are several alternatives out there but none will cover Lombok's features completely and work exactly the same way, so some code modifications and adjustments of expectations may be necessary.

Catnip makes heavy use of Lombok's Getters/Setters, Builders and Constructor annotations. This part of Lombok lends itself well to be replaced by the suggested immutables.org code generation lib.

### Show me the code
I have made a small proof of concept here: https://github.com/napstr/catnip/commit/2c6bda1b1de233d761d58fb56a74dc29a5c49da2


### Positive things:
- Catnip's existing codebase works very well with how the generated entities and builders look like and seems to only need minimal adjustments.
- We can reduce LoC and therefore maintenance by cutting the clutter of Lombok annotations and Impl classes.

### Risks uncovered:
- Some logic (example: `Presence#asJson`) has to move to the interfaces/abstract classes and may clutter them for end users.
- Serializing to / from JSON has not really been tested, more code may follow to make that work, ideally backed by tests.
- Sneaky bugs may happen: Currently, the Guilds `unavailable` and and `memberCount` default dynamic methods are always unconditionally overridden by the EntityBuilder adding static values from the JSON we received. This should probably only happen for when we directly request entities from the REST api.
- `equals`/`hashCode`/`toString` are autogenerated but not like we want them. We can provide our own however that is only possible if we change the interfaces to abstract classes.

**Comment by natanbc** [comment]
> Some logic (example: Presence#asJson) has to move to the interfaces/abstract classes and may clutter them for end users.

We can just move that to CatnipShard, which is the only class that uses those methods

**Comment by napstr** [comment]
Making sure that we are on the same page for stuffs, wrote up what I think are the requirements for the replacement to be considered a success:

- Smol and tidy interfaces for endusers (preferably without any breaking changes)
- Entities need to be (de)serializable through the event bus (via JSON)
- No lombok

Anything to add / change?

**Comment by queer** [comment]
I think that about covers it; one of our main uses of lombok was just to ensure consistency with method naming (ie. getters/setters are `x()`/`x(whatever)` rather than `getX()`/`setX(whatever)`, which we do to keep consistency with how Vert.x names such methods) but if Immutables can fill this need then I think it should be good :+1:

**Comment by napstr** [comment]
:ok_hand: added

**Comment by queer** [comment]
See also: #171
