### ISSUE TITLE
Hierarchy exception when adding a role that should be addable?

### ISSUE THREAD

**Issue by queer** [mewna/catnip#340]
Just ran into this earlier; bot with a high-position role w/ admin perms is supposedly unable to add a role below it in the hierarchy. Unsure why atm.

**Comment by itsTyrion** [comment]
Think I found it: 
the canInteract method (PermissionUtil:194) uses `actor.orderedRoles().iterator().next()`, but Member#orderedRoles returns the roles sorted from low to high, therefore it will compare the LOWEST self member role's position, instead of the highest one's. 
Might fix and pull request later..

**Comment by queer** [comment]
This was fixed in #380
